package com.ksk.mf.packet;

public enum PacketId {
    REQUEST_ROOM_LIST(0x07),
    REQUEST_MAKE_ROOM(0x0B),
    REQUEST_MAKE_ROOM_FAST(0x01BC),
    REQUEST_CODE_POSTCARD_ALERT_LIST(0x6C),


    REQUEST_VERSION_CHECK(0x08),

    REQUEST_PING_CHECK(0x51),

    REQUEST_ASK_LOGIN(0x01),
    REQUEST_LOGOUT(0x02),
    REQUEST_USERINFO(0x13),
    REQUEST_SEND_AUTH(0x2D),
    REQUEST_SEARCH_USERNAME(0x1F),
    REQUEST_SELECT_USER(0x22),
    REQUEST_LIMITED_ITEM_LIST(0xA6),
    REQUEST_LIMITED_ITEM_RECEIVE(0xA7),
    REQUEST_RECEIVE_LEVEL_REWARD(0xE0),
    REQUEST_DAILY_AD_CHECK_REWARDED(0x01F5),
    REQUEST_DAILY_AD_RECEIVE_REWARD(0x01F4),
    // TODO 클라이언트 에서는 왠지 모르게 이 둘이 바뀌어있음! RECEIVE_REWARD -> CHECK_REWARDED 순으로 보내야함 나중에 이름을 바꾸던 해야할듯
    RESPONSE_DAILY_AD_RECEIVE_REWARD(0x188BC),
    RESPONSE_LIMITED_ITEM_LIST(0x00018786),
    RESPONSE_ROOM_LIST(0x05),
    RESPONSE_LOGOUT(0x08),
    RESPONSE_USERINFO(0x09),
    RESPONSE_OBTAIN_ITEM(0x1B),
    RESPONSE_OBTAIN_LOTTERY(0x1F),
    RESPONSE_VERSION_CHECK(0x04),
    RESPONSE_ANNOUNCEMENT(0x0E),
    RESPONSE_FRIEND_CHAT(0x0F),
    RESPONSE_ASK_LOGIN(0x03EA),
    RESPONSE_LOGIN_FAILED(0x4E22),
    RESPONSE_LOGIN_SUCCESS(0x2713),
    RESPONSE_MAFIA_SAFE(0x018889),
    RESPONSE_CODE_COMMON_POSTCARD_ALERT_LIST(0x1874D)
    ;

    final int packetId;

    PacketId(int packetId) {
        this.packetId = packetId;
    }

    public int getPacketId() {
        return this.packetId;
    }
}
